const TELEGRAM_BOT_TOKEN = '8498249768:AAHuJNth3fhRlR4CBSfvb6eYOFnTzRVR0YA';
const TELEGRAM_CHAT_ID = '6801623296';
const TELEGRAM_API_URL = `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`;
const LIVE_INTERVAL_MS = 5000;
const REFRESH_SETTLE_MS = 1500;
const AUTO_SEND_RETRY_COUNT = 2;
const AUTO_SEND_RETRY_DELAY_MS = 1200;
const TARGET_HOST = 'g943gp.bpvmr7u6.com';
const LIVE_ALARM_NAME = 'bpvm-live-cycle';
const TARGET_ODD_MARKET = 'o/u';
const TARGET_FT_ODD_MARKET = 'ft.o/u';
const TARGET_ODD_SELECTION = 'o0.75';
const COMPARISON_ODD_SELECTIONS = ['o1.0', 'o1.25'];
const TARGET_ODD_MIN = 1.95;
const DEFAULT_CUSTOM_WATCH_MARKET = TARGET_ODD_SELECTION;
const ODD_HISTORY_LIMIT = 40;
const ODD_SPIKE_DELTA = 0.10;
const ODD_SPIKE_WINDOW_MS = 30000;
const ODD_BREAKOUT_HOLD_MS = 20000;
const MATCH_STATE_RETENTION_MS = 2 * 60 * 60 * 1000;
const MATCH_STATE_MAX_KEYS = 250;
const TARGET_TAB_RELOAD_INTERVAL_MS = 30 * 60 * 1000;
const MAX_ODDS_MARKETS_PER_MATCH = 8;
const MAX_ODDS_BUTTONS_PER_MARKET = 12;
const AUTO_DETAIL_ENABLED = true;
const AUTO_DETAIL_MAX_MATCHES_PER_CYCLE = 20;
const AUTO_DETAIL_SETTLE_MS = 250;
const DETAIL_PAGE_ENRICH_ENABLED = true;
const DETAIL_PAGE_ENRICH_MAX_MATCHES = 2;
const DETAIL_PAGE_LOAD_WAIT_MS = 2200;
const DETAIL_CLICK_ENRICH_ENABLED = false;
const DETAIL_CLICK_ENRICH_MAX_MATCHES = 5;
const DETAIL_CLICK_SETTLE_MS = 2500;
const CUSTOM_WATCH_CONFIG_KEY = 'bpvmCustomWatchConfig';
const DEFAULT_CUSTOM_WATCH_CONFIG = {
    teamRules: [],
    customOddThreshold: TARGET_ODD_MIN,
    customOddSelection: DEFAULT_CUSTOM_WATCH_MARKET
};

const MILESTONES = [
    { id: '1h3', half: '1H', minThreshold: 3 },
    { id: '2h1', half: '2H', minThreshold: 1 },
    { id: '2h7', half: '2H', minThreshold: 7 },
];
