<?php
return [
    'p24_teams' => ['Arminia Bielefeld (V)','CA Osasuna (V)','Arsenal (V)','Leicester City (V)','Borussia Dortmund (V)','Liverpool (V)','AS Monaco (V)','Olympique de Marseille (V)','Atalanta (V)','Tottenham Hotspur (V)','Everton (V)'],
    'p25_teams' => ['Real Sociedad (V)','France (V)','Netherlands (V)','Ukraine (V)'],
    'p28_teams' => ['Croatia (V)','France (V)'],
    'p35_teams' => ['Mexico (V)','Belgium (V)','Germany (V)','AS Monaco (V)','Wales  (V)','Portugal (V)','CA Osasuna (V)','Austria (V)','Poland (V)','Croatia (V)','Algeria (V)'],
    'p36_teams' => ['Paris Saint Germain (V)','Germany (V)','Mexico (V)','Belgium (V)'],
    'p61_teams' => ['Chelsea (V)','Lille OSC (V)','Juventus (V)','AS Monaco (V)'],
    'p62_teams' => ['Getafe CF (V)','CA Osasuna (V)','FC Koln (V)','Lazio (V)','Leicester City (V)','Napoli (V)','Sevilla (V)','Udinese (V)'],
    'p63_teams' => ['Belgium (V)','Germany (V)','Netherlands (V)','Norway (V)','Ghana (V)','Mexico (V)','Poland (V)','Portugal (V)'],
    'p64_teams' => ['Liverpool (V)','Napoli (V)','Bayern Munchen (V)','FC Koln (V)','FSV Mainz 05 (V)','Lille OSC (V)'],
    'p65_teams' => ['Leicester City (V)','Napoli (V)','Udinese (V)','Olympique Lyonnais (V)'],
    'p66_teams' => ['FSV Mainz 05 (V)','Getafe CF (V)','Lille OSC (V)','Liverpool (V)','Olympique Lyonnais (V)','Juventus (V)','Borussia Dortmund (V)','Napoli (V)','Bayern Munchen (V)','FC Koln (V)','Chelsea (V)'],
    'p67_teams' => ['Argentina (V)','Denmark (V)','Germany (V)','Russia (V)','Korea Republic (V)','Croatia (V)','Brazil (V)','Nigeria (V)','Serbia (V)','USA (V)','South Africa (V)','Portugal (V)','Oman (V)','New Zealand (V)','Philippines (V)','Iran (V)','Iraq (V)'],
    'lg4_teams' => ['Norway (V)','Uruguay (V)','Algeria (V)','Nigeria (V)','Romania (V)'],
    'lg5_teams' => ['France (V)','Spain (V)','Israel (V)','Morocco (V)'],
    'lg6_teams' => ['Indonesia (V)','Algeria (V)','Slovakia (V)','Slovenia (V)','Argentina (V)'],
    'lg7_teams' => ['Nigeria (V)','Qatar (V)','Slovenia (V)'],
    'lg8_teams' => ['Norway (V)','Nigeria (V)','Poland (V)','Slovenia (V)','Romania (V)','Argentina (V)','India (V)','Belgium (V)'],
];
